services:
  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_DB: my_cube
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d my_cube"]
      interval: 5s
      timeout: 3s
      retries: 20

  web:
    build: .
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_DB: my_cube
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      HOST_IP: ${HOST_IP:-}
      DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1,111.88.150.97,3dspeedcubing.ru,www.3dspeedcubing.ru
      DJANGO_CSRF_TRUSTED_ORIGINS: http://localhost:8000,http://127.0.0.1:8000,http://3dspeedcubing.ru,http://www.3dspeedcubing.ru,https://3dspeedcubing.ru,https://www.3dspeedcubing.ru
    ports:
      - "80:8000"
      - "8000:8000"
    volumes:
      - ./:/app
      - ../frontend_repo/templates/main:/app/main/templates/main:ro
      - ../frontend_repo/static/main:/app/main/static/main:ro
    command: sh -c "python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data:
