# Generated by Django 5.2 on 2026-03-30 16:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_reset_legacy_default_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('player', 'Игрок'), ('spectator', 'Зритель'), ('organizer', 'Организатор')], default='player', max_length=16, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='personalrecordattempt',
            name='solve_time_seconds',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999.99)], verbose_name='Время сборки'),
        ),
        migrations.AlterField(
            model_name='publicrecordattempt',
            name='solve_time_seconds',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999.99)], verbose_name='Время сборки'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название комнаты')),
                ('max_players', models.PositiveSmallIntegerField(default=2, verbose_name='Лимит игроков')),
                ('max_spectators', models.PositiveSmallIntegerField(default=8, verbose_name='Лимит зрителей')),
                ('start_mode', models.CharField(choices=[('owner', 'По решению создателя'), ('all_invited', 'Когда соберутся все приглашенные')], default='owner', max_length=16, verbose_name='Старт игры')),
                ('countdown_seconds', models.PositiveSmallIntegerField(default=5, verbose_name='Отсчет перед стартом (сек)')),
                ('fade_in_seconds', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=4, verbose_name='Fade In (сек)')),
                ('fade_out_seconds', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=4, verbose_name='Fade Out (сек)')),
                ('study_seconds', models.PositiveSmallIntegerField(default=10, verbose_name='Период изучения (сек)')),
                ('status', models.CharField(choices=[('waiting', 'Ожидание'), ('running', 'Игра идет'), ('finished', 'Завершена')], default='waiting', max_length=16, verbose_name='Статус комнаты')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RoomInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_role', models.CharField(choices=[('organizer', 'Организатор'), ('player', 'Игрок'), ('spectator', 'Зритель')], max_length=16, verbose_name='Приглашение как')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принято'), ('declined', 'Отклонено')], default='pending', max_length=16, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_room_invitations', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_room_invitations', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='main.room')),
            ],
            options={
                'verbose_name': 'Приглашение в комнату',
                'verbose_name_plural': 'Приглашения в комнаты',
                'unique_together': {('room', 'invitee')},
            },
        ),
        migrations.CreateModel(
            name='RoomParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('organizer', 'Организатор'), ('player', 'Игрок'), ('spectator', 'Зритель')], max_length=16, verbose_name='Роль в комнате')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='main.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Участник комнаты',
                'verbose_name_plural': 'Участники комнат',
                'unique_together': {('room', 'user')},
            },
        ),
    ]
