# Generated by Django 5.2 on 2026-03-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_userprofile_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalrecordattempt',
            name='source',
            field=models.CharField(
                choices=[('single', 'single'), ('room', 'room')],
                default='single',
                max_length=16,
                verbose_name='Источник попытки',
            ),
        ),
    ]
