# Generated by Django 5.2 on 2026-03-31 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_personalrecordattempt_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CubeState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cube_materials', models.TextField(blank=True, default='', verbose_name='Состояние материалов куба')),
                ('skin_state', models.JSONField(blank=True, default=dict, verbose_name='Состояние скина')),
                ('additional_info', models.JSONField(blank=True, default=dict, verbose_name='Дополнительная информация')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cube_state', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Состояние куба',
                'verbose_name_plural': 'Состояния кубов',
            },
        ),
    ]
